"""Build seed material (markdown documents) for MiroFish simulations."""

from datetime import datetime

from xprclaw_mirofish.models import MarketState, ScenarioType
from xprclaw_mirofish.personas import get_all_personas


def _round_hour(dt: datetime) -> datetime:
    """Round datetime down to the hour for cache stability."""
    return dt.replace(minute=0, second=0, microsecond=0)


def build_seed(state: MarketState, scenario: ScenarioType) -> str:
    """Build markdown seed material for MiroFish simulation.

    Returns a deterministic markdown document. Same (state, scenario) always
    produces byte-identical output (important for content-hash caching).
    """
    personas = get_all_personas()
    rounded_ts = _round_hour(state.timestamp)

    # Build persona list for the seed
    persona_list = "\n".join(
        f"- **{p.name}** ({p.id}): {p.description} "
        f"[Bias: {p.bias}, Risk: {p.risk_tolerance:.1f}, "
        f"Horizon: {p.time_horizon_days}d]"
        for p in personas
    )

    # Scenario-specific context
    scenario_context = _get_scenario_context(scenario, state)

    # External events (if any)
    external_events_block = ""
    if state.external_news:
        external_events_block = "\n\n## External Events\n"
        for i, news in enumerate(state.external_news, 1):
            external_events_block += f"{i}. {news}\n"

    # Format timestamp as ISO string without timezone suffix (already rounded)
    ts_str = rounded_ts.replace(tzinfo=None).isoformat()

    seed = f"""# XPRClaw Market Simulation Seed

**Scenario:** {scenario.value}
**Timestamp:** {ts_str}Z
**Generated by:** xprclaw-mirofish@0.1.0

## Market State

| Metric | Value |
|--------|-------|
| XPR Price (USD) | ${state.xpr_price_usd:.6f} |
| Staking APY | {state.staking_apy*100:.2f}% |
| Loan APY | {state.loan_apy*100:.2f}% |
| Metal X Spread (bps) | {state.metalx_xpr_usd_spread_bps:.1f} |
| Treasury XPR | {state.treasury_xpr:,.0f} XPR |
| Open Loan XPR | {state.open_loan_xpr:,.0f} XPR |

## Agent Personas

The following six agents will participate in the simulation:

{persona_list}

## Scenario Briefing

{scenario_context}{external_events_block}

## Instructions for Agents

1. Each agent acts according to their persona bias and risk tolerance.
2. Consider the market state when forming opinions and making decisions.
3. Respond to external events if relevant to your strategy.
4. The simulation will run for multiple rounds; adapt your position as conditions change.
5. Report your reasoning transparently; other agents may respond to your signals.

---

*Seed generated deterministically. Same market state + scenario = identical markdown.*
"""
    return seed


def _get_scenario_context(scenario: ScenarioType, state: MarketState) -> str:
    """Return scenario-specific briefing text."""
    if scenario == ScenarioType.STAKING_OPTIMIZATION:
        return (
            "**Question:** Should we increase, maintain, or decrease our XPR staking position?\n\n"
            f"Current staking yield is {state.staking_apy*100:.2f}% APY. "
            f"Loan cost is {state.loan_apy*100:.2f}% APY. "
            f"Consider XPR price direction, opportunity cost, and collateral needs."
        )
    elif scenario == ScenarioType.LOAN_MANAGEMENT:
        return (
            "**Question:** Should we open, resize, or close our Proton Loan?\n\n"
            f"We currently have {state.open_loan_xpr:,.0f} XPR borrowed at {state.loan_apy*100:.2f}% APY. "
            f"Staking yields {state.staking_apy*100:.2f}% APY. "
            f"Consider leverage, liquidation risk, and capital efficiency."
        )
    elif scenario == ScenarioType.ARBITRAGE_WINDOW:
        return (
            "**Question:** Is the current Metal X spread wide enough to exploit?\n\n"
            f"Metal X XPR/USD spread: {state.metalx_xpr_usd_spread_bps:.1f} bps. "
            f"XPR price: ${state.xpr_price_usd:.6f}. "
            f"Consider gas costs, execution speed, and market depth."
        )
    elif scenario == ScenarioType.TREASURY_REBALANCE:
        return (
            "**Question:** Should we rebalance between XPR, stables, and collateral?\n\n"
            f"Treasury holds {state.treasury_xpr:,.0f} XPR worth ${state.treasury_xpr * state.xpr_price_usd:,.0f}. "
            f"Consider diversification, staking vs holding, and runway."
        )
    else:  # NEWS_REACTION
        return (
            "**Question:** How should we react to recent external events?\n\n"
            "The market has moved on new information. Assess whether this represents "
            "genuine risk, a temporary overreaction, or an opportunity."
        )
